### PR TITLE
ARIES-1826 Bump xbean-finder from 4.5 to 4.9

### PR DESCRIPTION
**Pull request by vorburger**
see https://jira.apache.org/jira/browse/ARIES-1826

### CODE REVIEW

**Comment by vorburger** [comment]
@cschneider @gnodet @grgrzybek @bosschaert @timothyjward @jbonofre would one of you be willing to merge this and release a blueprint-maven-plugin 1.10.1 with this soon-ish? This is blocking us over in https://opendaylight.org ... thanks!

**Comment by jbonofre** [comment]
@vorburger thanks for the update. Let me check the change.

**Review by jbonofre — APPROVED** [review]
LGTM, thanks !

**Comment by jbonofre** [comment]
It looks good to me. I will merge.

**Comment by cschneider** [comment]
LGTM .. but I currently do not have a working git svn setup for aries. So I am glad if JB does the merge.

**Comment by jbonofre** [comment]
No problem I will tackle the merge just after lunch.

**Pull request closed without merging**
