### PR TITLE
[ARIES-1164] Fixed integration test

### PR DESCRIPTION
**Pull request by grgrzybek**

### CODE REVIEW

**Comment by bosschaert** [comment]
Looks good to me.

**Comment by bosschaert** [comment]
I was running the Aries Blueprint tests and noticed that it needs access to [mvn:org.junit/com.springsource.org.junit/4.4.0], which is not included in the listed repositories in the parent pom. 

In any case, when I add that in as a dependency, the test still hangs as below. Are you getting this too?

`<error message="Cannot get the remote bundle context" type="org.ops4j.pax.exam.spi.container.TestContainerException">org.ops4j.pax.exam.spi.container.TestContainerException: Cannot get the remote bundle context
    at org.ops4j.pax.exam.rbc.client.RemoteBundleContextClient.getRemoteBundleContext(RemoteBundleContextClient.java:324)
    at org.ops4j.pax.exam.rbc.client.RemoteBundleContextClient.waitForState(RemoteBundleContextClient.java:265)
    at org.ops4j.pax.exam.container.def.internal.PaxRunnerTestContainer.waitForState(PaxRunnerTestContainer.java:346)
    at org.ops4j.pax.exam.container.def.internal.PaxRunnerTestContainer.start(PaxRunnerTestContainer.java:290)
    at org.ops4j.pax.exam.junit.internal.JUnit4TestMethod.invoke(JUnit4TestMethod.java:142)
    at org.junit.internal.runners.MethodRoadie.runTestMethod(MethodRoadie.java:105)
    at org.junit.internal.runners.MethodRoadie$2.run(MethodRoadie.java:86)
    at org.ops4j.pax.exam.junit.internal.JUnit4MethodRoadie.runBeforesThenTestThenAfters(JUnit4MethodRoadie.java:60)
    at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:84)
    at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:49)
    at org.ops4j.pax.exam.junit.JUnit4TestRunner.invokeTestMethod(JUnit4TestRunner.java:246)
    at org.ops4j.pax.exam.junit.JUnit4TestRunner.runMethods(JUnit4TestRunner.java:196)
    at org.ops4j.pax.exam.junit.JUnit4TestRunner$2.run(JUnit4TestRunner.java:186)
    at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:34)
    at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:44)
    at org.ops4j.pax.exam.junit.JUnit4TestRunner.run(JUnit4TestRunner.java:182)
    at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:62)
    at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:140)
    at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:165)
    at org.apache.maven.surefire.Surefire.run(Surefire.java:107)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:289)
    at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1005)
Caused by: java.rmi.ConnectException: Connection refused to host: 192.168.1.6; nested exception is: 
    java.net.ConnectException: Operation timed out
    at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:601)
    at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:198)
    at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:184)
    at sun.rmi.server.UnicastRef.newCall(UnicastRef.java:322)
    at sun.rmi.registry.RegistryImpl_Stub.lookup(Unknown Source)
    at org.ops4j.pax.exam.rbc.client.RemoteBundleContextClient.getRemoteBundleContext(RemoteBundleContextClient.java:302)
    ... 25 more
Caused by: java.net.ConnectException: Operation timed out
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:382)
    at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:241)
    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:228)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:431)
    at java.net.Socket.connect(Socket.java:527)
    at java.net.Socket.connect(Socket.java:476)
    at java.net.Socket.&lt;init&gt;(Socket.java:373)
    at java.net.Socket.&lt;init&gt;(Socket.java:187)
    at sun.rmi.transport.proxy.RMIDirectSocketFactory.createSocket(RMIDirectSocketFactory.java:22)
    at sun.rmi.transport.proxy.RMIMasterSocketFactory.createSocket(RMIMasterSocketFactory.java:128)
    at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:595)
    ... 30 more
</error>`

**Comment by grgrzybek** [comment]
Hmm, no, I have nice:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.apache.aries.blueprint.itests.TestRegistrationListener
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.642 sec
Running org.apache.aries.blueprint.itests.BlueprintContainerTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 45.631 sec
Running org.apache.aries.blueprint.itests.FragmentTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.553 sec
Running org.apache.aries.blueprint.itests.TestConfigAdmin
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 9.666 sec
Running org.apache.aries.blueprint.itests.BlueprintContainerBTCustomizerTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 9.348 sec
Running org.apache.aries.blueprint.itests.BlueprintContainer2Test
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.85 sec
Running org.apache.aries.blueprint.itests.BlueprintContainer2BTCustomizerTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 10.813 sec
Running org.apache.aries.blueprint.itests.QuiesceBlueprintTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 19.323 sec
Running org.apache.aries.blueprint.itests.ASMMultiBundleTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.835 sec
Running org.apache.aries.blueprint.itests.MultiInterfacesTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.82 sec
Running org.apache.aries.blueprint.itests.TestReferences
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 16.192 sec

Results :

Tests run: 24, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- maven-enforcer-plugin:1.0-beta-1:enforce (check-java15) @ org.apache.aries.blueprint.itests ---
[INFO] Checking unresolved references to org.codehaus.mojo.signature:java15:1.0
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:17 min
[INFO] Finished at: 2014-03-27T11:58:45+01:00
[INFO] Final Memory: 14M/423M
[INFO] ------------------------------------------------------------------------
```

I spotted that I had `~/.m2/repository/org/junit/com.springsource.org.junit/4.4.0/com.springsource.org.junit-4.4.0.jar`, but when I removed it the tests were still ok (and the artifact was not downloaded again.

btw, you can chat me at freenode/#apache-aries

regards
Grzegorz Grzybek

**Comment by bosschaert** [comment]
It seems related to the fact that I was using Java 6... With Java 7 it works for me...

**Comment by grgrzybek** [comment]
Great ;)

**Comment by bosschaert** [comment]
@grgrzybek please close the pull request if satisfied.

**Pull request closed without merging**
