### PR TITLE
adding comments with issue numbers.

### PR DESCRIPTION
**Pull request by ackelcn**
https://issues.apache.org/jira/browse/ARIES-1988

I created this pull request to highlight the new comments.

### CODE REVIEW

**Comment by cschneider** [comment]
Why should that be a good idea? You can look in github which lines were changed by which commit. Adding comments everywhere is like commenting every single line of code.

**Comment by jbonofre** [comment]
I agree with @cschneider not sure it's worth to add bunch of comments and "noise". -1 about this PR.

**Comment by ackelcn** [comment]
Indeed, my tool does not comment every line. It comments only those snippets that can be traced to a specifc commit. The comments link the code lines to issue reports, and shall be useful to understand code. 
I agree that some comments may describe too simple code lines, but shall we still accept comments on those complicated ones?

**Comment by rmannibucau** [comment]
@ackelcn I know some people like this kind of tools, some don't so I wonder if you shouldn't push your tool to the next step and make it an intellij (or eclipse) plugin (a bit like "annotate"/"blame" features) which would preppend/append the issue as a link to the commit - extracting the issue from the commit. It would make everyone happy and would make the usage more straight forward IMHO.

**Comment by cschneider** [comment]
It totally agree with Romain. Instead of adding the comments to the code you could add them on the fly while viewing the code. Apart from eclipse and idea plugins you could also create a github plugin.

**Comment by ackelcn** [comment]
Perhaps, instead of writting them in code comments, my tool shall store links and highlight the corresponding commits, when a programmers is interesting in a specific code line? So, shall my tool works like this? When you click a code line, it then presents a window to show the issue reports and commits.

**Comment by rmannibucau** [comment]
Have to admit i'm not an user of that but if not already supported jira plugin (https://plugins.jetbrains.com/plugin/11169-jira-integration) sounds like a good way to get that feature quite smoothly. Will likely need some context menu/annotate integration but it has already all you need to make it smooth.

Just my 2cts indeed

**Comment by cschneider** [comment]
`When you click a code line, it then presents a window to show the issue reports and commits.`

Yes. It could work like this.

`I agree that some comments may describe too simple code lines, but shall we still accept comments on those complicated ones?`

I think it is like with comments in general. You put them were you think that additional explanations are required to understand the code.  At the same time every comment is a liability. Comments tend to rott as they are not tested by junit. So over time a comment might describe something that is not matching the changed code anymore at all. This is why I favour improving the code instead of adding many comments. 

Jiras can be used to track and explain the requirements. So sometimes links to them make sense. Unfortunately they do not track the changes over time. So possibly a jira represents a requirement at some point in time but later the requirement might have vanished or changed. The old jira issue will not reflect this. So adding the link is easy and can be automated as you demonstrate with your tool. Managing the link over time is much harder. 

This is why I think adding the links on the fly while viewing from the blame feature is better. When the code is changed because of changed requirements then the on the fly tool will automatically change to the new jiras.

**Comment by ackelcn** [comment]
Hi, cschneider, I agree with you that comments can become out-of-date, but my comments are automatically geneated.  It shall be easy to totally remove my generated comments, and re-generate them to keep them up-to-date. Perhaps, I shall find a better way to manage manual comments and my generated comments. It can be a better way to present automatic comments when there is no manual comment and programmers do some comments. Here, they can click a bottom, and my tool show its generated comments. 

I also agree with you that some issue reports can be invalid. When I implement my tool, I found some cases where the changes of an issue report are totally rewritten by follow-up changes. Are those issue reports one type of your mentioned invalid JIRA issues? Is a tool useful, if that tool can find those invalid issue reports for you?

**Comment by cschneider** [comment]
I think the idea of adding the links to jira isssues in the code is flawed. Instead add them while viewing. Basically it is simply an improved "blame" view.

The blame view also kind of automates that issues are not linked anymore when all their code lines are replaced by newer commits. So I think this can sort itself out automatically in most cases.

Jira is simply not meant to be a good requirements tool. So I think it is normal that older jira issues might not represent the current requirements anymore.

**Comment by rotty3000** [comment]
I agree with @cschneider so since we've had not other feedback on this for a long time lets close it.

However, we do appreciate the contribution and interest :)

**Pull request closed without merging**
