### PR TITLE
[aries-1612] Zip input stream relies on default (non buffered) InputS…

### PR DESCRIPTION
**Pull request by paulthvt**
Fix of the [[aries-1612]](https://issues.apache.org/jira/browse/ARIES-1612) issue.

### CODE REVIEW

**Comment by tjwatson** [comment]
I merged the fix into aries SVN.  Thanks.  I'm unsure why I cannot seem to close this pull request.

**Comment by tomdw** [comment]
Who can make a release of aries util?

**Comment by tomdw** [comment]
@tjwatson I can't find these commits on the trunk of aries on this github mirror. Sure you merged it into aries SVN?

**Comment by tjwatson** [comment]
The fix is in trunk.  See: http://svn.apache.org/viewvc/aries/trunk/util/util-r42/src/main/java/org/apache/aries/util/filesystem/impl/ZipFileImpl.java?r1=1760753&r2=1760752&pathrev=1760753

**Comment by tomdw** [comment]
@tjwatson thx, what is the differnce between the util-r42 and the util directories? Which of the 2 is part of the next release? @bosschaert can you provide a new util release including this change?

**Comment by tjwatson** [comment]
My understanding of the two directories is that they both are use to create the util bundle.   But the r42 one can be used to create a util bundle that can run on a R4.3 framework.  This is likely obsolete and the two folders should likely be combined.

**Comment by tomdw** [comment]
Should the change then be applied in both directories?

**Comment by cschneider** [comment]
I started a discussion to merge the two util bundles. Do you think we can close this PR?

**Comment by cschneider** [comment]
The two util bundles are now merged into one. I will close this PR if there is no other feedback.

**Pull request closed without merging**
