### PR TITLE
ARIES-1047 JPA 2.1 support

### PR DESCRIPTION
**Pull request by brmeyer**

### CODE REVIEW

**Comment by pires** [comment]
+1

Given this is a mirror from the official Git, am I wrong to assume this is not getting merged?

**Comment by bosschaert** [comment]
We are trying to get pull requests merged. However, I'm not familiar enough with the JPA area to properly review this pull request. Maybe someone else can provide a review?

**Comment by jbonofre** [comment]
+1

**Comment by ieugen** [comment]
+1. The auto-generated stubs should be there?

**Comment by cschneider** [comment]
Is this pr still valid? I think we already have jpa 2.1 support now. Btw. Sorry for not looking into this earlier. I just got familiar with pull requests in the recent months.

**Comment by cschneider** [comment]
I will close this PR. Please reopen if it is still relevant.

**Pull request closed without merging**
