### PR TITLE
[ARIES-1570] Create SPI and move spring annotations to separate package

### PR DESCRIPTION
**Pull request by alien11689**

### CODE REVIEW

**Comment by cschneider** [comment]
Great that you did a PR for this bigger change. I almost missed it though. Can you open a discuss thread on the dev list so we can also get feedback from others?

**Comment by cschneider** [comment]
Can you squash the commits into one. That makes it easier to review.

**Comment by alien11689** [comment]
I have written an email about this PR when I have created PR. It was in the same thread, in which github has sent information about PR.

I will squash the commits and send the email one more time.

**Comment by alien11689** [comment]
The commits are squashed and the email was sent

**Comment by cschneider** [comment]
After a quick review the spi change looks pretty good. I am sure there are improvement points but nothing that should hold a merge from my point of view. Lets give it some time for others to comment.

**Comment by alien11689** [comment]
There is no more comments, so I close PR and merge it to trunk

**Comment by alien11689** [comment]
Merged in https://svn.apache.org/viewvc?view=revision&revision=1750823

**Pull request closed without merging**
