### PR TITLE
Add constructor injection and component name in reference

### PR DESCRIPTION
**Pull request by alien11689**

### CODE REVIEW

**Comment by alien11689** [comment]
https://issues.apache.org/jira/browse/ARIES-1501

**Comment by cschneider** [comment]
Most of the code looks good but there are two things:
- We can not simply introduce lombok. This would require a discussion on the dev list. For example in my eclipse the project did not compile anymore. So if you want to introduce this then you need to get backing by the aries community first. 
  As for this case the improvements in lines of code is not that big I propose you rewrite to plain java. At the same time you can start a discuss on dev of course.
- Your commits do not reference the issue. Please always use a commit message like "[ARIES-1501] your text"

**Comment by alien11689** [comment]
Hi,
I have removed lombok and I have added issue reference to commit message.

**Comment by alien11689** [comment]
Merged mannually by @cschneider in https://github.com/apache/aries/commit/218954f09e8728ac5610e5352e634b1b0d3a31b5

**Pull request closed without merging**
