### PR TITLE
ARIES-1590 ARIES-1591, ARIES-1588 fix regression in resolving subsystems

### PR DESCRIPTION
**Pull request by tomdw**
Fixes ARIES-1590, ARIES-1591, ARIES-1588

### CODE REVIEW

**Comment by tomdw** [comment]
@tjwatson @bosschaert  fixes 3 blocking bugs for the subsystem 2.1.0 release

**Comment by tomdw** [comment]
Some explanation:
- the changes for ARIES-1443 resulted in too much regression blocking a new release
- I partly reverted them but still kept the fix for ARIES-1442 by not including the identity of constituents
- also excluded the host capability as the subsystem does not need to impersonate as a host of a fragment either

The reverted code only impacted the capabilities during install of a completely new subsystem. No further impact.

**Comment by cschneider** [comment]
What is the status of this PR? I am a bit puzzled by the many linked issues. Some of these issues seem to be resolved already. I was also not able to merge this in my git svn.

**Comment by tomdw** [comment]
@cschneider When looking at https://svn.apache.org/viewvc?view=revision&revision=1787137 it seems that the changes of this pull request are already included. Maybe double check and then this pull request was already merged by that commit on svn.

**Comment by cschneider** [comment]
Yes. I also think so. Can you close it? In case anything is still missing you can commit it yourself anyway.

**Pull request closed without merging**
