### PR TITLE
Add support of jdk11 build for versioning

### PR DESCRIPTION
**Pull request by olamy**

### CODE REVIEW

**Comment by bosschaert** [comment]
This PR is still open, but it seems like the issue is already resolved https://issues.apache.org/jira/browse/ARIES-1844 ? If so can we close this PR?

**Comment by joakime** [comment]
@bosschaert the changes here look different then the ones reported on https://issues.apache.org/jira/browse/ARIES-1844

@olamy has made some code changes in various Java files, while the changes in https://svn.apache.org/viewvc?view=revision&revision=1845283 had none.

**Comment by olamy** [comment]
@bosschaert @joakime with those changes you can even now build using jdk11. One more step to jdk11 compliance :) that's my remaining changes while I was working on ARIES-1844. 
But you guys committed before I opened the pr. So it's the leftover of my jdk11 work after rebase (it's only about versioning project)
Take it or not but I think you will need it in the future :)

**Comment by olamy** [comment]
@bosschaert @jbonofre any plan for a release soon or deploying snapshots to repository.a.o for https://issues.apache.org/jira/browse/ARIES-1844 ? Thanks guys

**Comment by jbonofre** [comment]
@olamy yes, I gonna prepare a new release focus on Java 11 support.

**Comment by olamy** [comment]
@jbonofre Thanks  buddy! ATM the Jetty project really depends on it to release 10.0.x series (servlet 4.0 specs).

**Comment by cschneider** [comment]
Hi Olivier. Seems this PR is broken after our move to git. Can you recreate it based on current trunk?

**Pull request closed without merging**
