### PR TITLE
initial spike of ARIES-1038 so that blueprint-noosgi can be easily used ...

### PR DESCRIPTION
**Pull request by jstrachan**
...inside a servlet engine without an OSGi environment; but booting up all the META-INF/blueprint.xml files and performing the DI on everything using blueprint-noosgi

### CODE REVIEW

**Comment by pires** [comment]
This is just a mirror. They will never merge anything from here :-1:

**Comment by bosschaert** [comment]
Apologies, that comment referenced the wrong pull request. It closes #7 instead. So much for the manual steps in getting this back into SVN :(

**Comment by bosschaert** [comment]
Is this pull request still relevant or can it be closed?

**Comment by jstrachan** [comment]
I guess it can be closed as the underlying issue is fixed https://issues.apache.org/jira/browse/ARIES-1038

**Pull request closed without merging**
